yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<post_id>/', views.post_detail, name='post_detail'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

NUM_SYMB = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        help_text='Загрузите картинку',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:NUM_SYMB]

    class Meta:
        default_related_name = 'posts'
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Добавить комментарий'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:NUM_SYMB]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор подписки'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'text': 'текст поста',
            'group': 'наименование группы',
        }
        help_texts = {
            'text': 'текст нового поста',
            'group': 'группа поста',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'комментарий',
        }
        help_texts = {
            'text': 'текст комментария',
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from .utilities import get_paginator

CACHE_TIME = 20


@cache_page(CACHE_TIME)
def index(request):
    post_list = Post.objects.select_related('author', 'group')
    return render(request, 'posts/index.html', context={
        'title': 'Последние обновления на сайте',
        'page_obj': get_paginator(post_list, request), })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    return render(request, 'posts/group_list.html', context={
        'group': group,
        'page_obj': get_paginator(post_list, request), })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group')
    posts_count = post_list.count()
    following = request.user.is_authenticated
    if following:
        following = author.following.filter(user=request.user).exists()
    return render(request, 'posts/profile.html', context={
        'author': author,
        'posts_count': posts_count,
        'following': following,
        'page_obj': get_paginator(post_list, request), })


def post_detail(request, post_id):
    post_item = get_object_or_404(
        Post.objects.select_related('group', 'author'), pk=post_id
    )
    form = CommentForm()
    comments = post_item.comments.select_related('author')
    return render(request, 'posts/post_detail.html', context={
        'post_item': post_item,
        'form': form,
        'comments': comments})


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context={
            'form': form, 'is_edit': False})
    post = form.save(commit=False)
    post.author = request.user
    form.save()
    user_name = request.user.username
    return redirect('posts:profile', user_name)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if post.author == request.user:
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', context={
        'form': form, 'is_edit': True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author'),
        pk=post_id
    )
    form = CommentForm(request.POST or None)
    if not form.is_valid():
        return redirect('posts:post_detail', post_id=post_id)
    comment = form.save(commit=False)
    comment.author = request.user
    comment.post = post
    comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follow_posts = Post.objects.filter(author__following__user=request.user)
    return render(request, 'posts/follow.html', context={
        'title': 'Посты с подписками',
        'page_obj': get_paginator(follow_posts, request), })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
   <title>Редактирование поста</title>
   {% else %}
   <title>Новая запись</title>
  {% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Новая запись
                {% endif %}
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="group">
                        <br>
                        {{ field }}
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        <label>{{ field.label }}</label>
                        <span>{{ field.errors }}</span>
                        {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-texts text-muted">
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <br>
                    {% if is_edit %}
                    <button type="submit" class="btn btn-primary">
                        Сохранить
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">
                        Добавить
                    </button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>{{ title }}</title>
{% endblock %}
{% block content %}
{% load static %}
    <div class="container mt-3">
      <h1>{{ title }}</h1>
        {% include 'posts/includes/switcher.html' with follow=True %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "1000x1000" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            <br>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}<title>Последние сообщения в группе {{ group.title }}</title>{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaks }}</p>
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  <br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}
  <hr>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>{{ title }}</title>
{% endblock %}
{% block content %}
{% load static %}
    <div class="container mt-3">
      <h1>{{ title }}</h1>
        {% include 'posts/includes/switcher.html' with index=True %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "1000x1000" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            <br>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  <title>Пост {{ post_item.text|truncatewords:30 }}</title>
{% endblock %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post_item.pub_date|date:"d E Y" }}
                </li>
                <li class="list-group-item">
                    Группа: {{ post_item.group.title }}
                    {% if post_item.group %}
                    <a href="{% url 'posts:group_list' post_item.group.slug %}">
                        все записи группы
                    </a>
                    {% endif %}
                </li>
                <li class="list-group-item">
                    Автор: {{ post_item.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span>{{ post_item.author.posts.count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post_item.author.username %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            <div class="card-body">
                {% thumbnail post_item.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>{{ post_item.text }}</p>
                {% if request.user == post_item.author %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post_item.pk %}">
                    редактировать запись
                </a>
                {% endif %}
            </div>
        </article>
        {% include 'posts/includes/add_comment.html' %}
    </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>Все посты пользователя {{ author.get_full_name }} </title>
{% endblock %}
{% block content %}
    <div class="container mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ posts_count }} </h3>
        {% if following %}
        <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
            Отписаться
        </a>
        {% else %}
        <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
            Подписаться
        </a>
        {% endif %}
        {% for post in page_obj %}
         <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
             {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
             {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          </article>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}